import { User, Course, Exam, ExamSubmission, Announcement, SchoolInfo } from '../types';

export const initialSchoolInfo: SchoolInfo = {
  schoolName: 'โรงเรียนบ้านคลองพลูประชาสรรค์',
  schoolSubName: 'สำนักงานเขตพื้นที่การศึกษาประถมศึกษา',
  academicYear: '2568',
  semester: '1',
  directorName: 'นายไพบูลย์ วงค์เมืองคำ',
  directorTitle: 'ผู้อำนวยการโรงเรียนบ้านคลองพลูประชาสรรค์',
  phone: '038-123-456',
  email: 'kps.prachasan@gmail.com',
  address: 'โรงเรียนบ้านคลองพลูประชาสรรค์',
  logoUrl: '',
};

export const initialUsers: User[] = [
  // 1. Director / ผู้อำนวยการ (Super Admin)
  {
    id: 'usr-4197',
    username: '4197',
    password: '114124',
    titlePrefix: 'นาย',
    firstName: 'ไพบูลย์',
    lastName: 'วงค์เมืองคำ',
    fullName: 'นายไพบูลย์ วงค์เมืองคำ',
    role: 'director',
    email: 'kps.prachasan@gmail.com',
    phone: '081-419-7000',
    employeeId: 'DIR-4197',
    positionTitle: 'ผู้อำนวยการโรงเรียน (Super Admin)',
    department: 'ฝ่ายบริหารงานโรงเรียน',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=4197',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },

  // 2. Teachers / คณะครู
  {
    id: 'usr-5106',
    username: '5106',
    password: '123456',
    titlePrefix: 'นาย',
    firstName: 'กล้านรงค์',
    lastName: 'ศิรินโรจน์',
    fullName: 'นายกล้านรงค์ ศิรินโรจน์',
    role: 'teacher',
    email: 'teacher5106@kps.ac.th',
    phone: '089-510-6001',
    employeeId: '5106',
    positionTitle: 'ครู คศ.2',
    department: 'ฝ่ายวิชาการ / หัวหน้ากลุ่มสาระ',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=5106',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-5212',
    username: '5212',
    password: '123456',
    titlePrefix: 'นางสาว',
    firstName: 'อุมา',
    lastName: 'จ่อมจันทร์',
    fullName: 'นางสาวอุมา จ่อมจันทร์',
    role: 'teacher',
    email: 'teacher5212@kps.ac.th',
    phone: '089-521-2002',
    employeeId: '5212',
    positionTitle: 'ครู คศ.1',
    department: 'ฝ่ายวิชาการ / กลุ่มสาระภาษาไทย',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=5212',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-4302',
    username: '4302',
    password: '123456',
    titlePrefix: 'นางสาว',
    firstName: 'จิรวัฒนา',
    lastName: 'เบ้าศิลป์',
    fullName: 'นางสาวจิรวัฒนา เบ้าศิลป์',
    role: 'teacher',
    email: 'teacher4302@kps.ac.th',
    phone: '089-430-2003',
    employeeId: '4302',
    positionTitle: 'ครู คศ.1',
    department: 'ฝ่ายวิชาการ / กลุ่มสาระคณิตศาสตร์',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=4302',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-4294',
    username: '4294',
    password: '123456',
    titlePrefix: 'นางสาว',
    firstName: 'ชมพูนุท',
    lastName: 'วิชัยปะ',
    fullName: 'นางสาวชมพูนุท วิชัยปะ',
    role: 'teacher',
    email: 'teacher4294@kps.ac.th',
    phone: '089-429-4004',
    employeeId: '4294',
    positionTitle: 'ครู คศ.1',
    department: 'ฝ่ายวิชาการ / กลุ่มสาระวิทยาศาสตร์',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=4294',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-4305',
    username: '4305',
    password: '123456',
    titlePrefix: 'นางสาว',
    firstName: 'ชนกเนตร',
    lastName: 'ทระคำหาร',
    fullName: 'นางสาวชนกเนตร ทระคำหาร',
    role: 'teacher',
    email: 'teacher4305@kps.ac.th',
    phone: '089-430-5005',
    employeeId: '4305',
    positionTitle: 'ครูผู้ช่วย / ครูอัตราจ้าง',
    department: 'ฝ่ายวิชาการ / กลุ่มสาระภาษาต่างประเทศ',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=4305',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-t1',
    username: 'T-Teacher1',
    password: '123456',
    titlePrefix: 'นาย',
    firstName: 'ศุภกันต์',
    lastName: 'วันดี',
    fullName: 'นายศุภกันต์ วันดี',
    role: 'teacher',
    email: 'teacher1@kps.ac.th',
    phone: '089-100-1111',
    employeeId: 'TCH-T1',
    positionTitle: 'ครูผู้สอน',
    department: 'ฝ่ายวิชาการ / สังคมศึกษา',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=T-Teacher1',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-t2',
    username: 'T-Teacher2',
    password: '123456',
    titlePrefix: 'นางสาว',
    firstName: 'วรรณภา',
    lastName: 'สุขเจริญ',
    fullName: 'นางสาววรรณภา สุขเจริญ',
    role: 'teacher',
    email: 'teacher2@kps.ac.th',
    phone: '089-200-2222',
    employeeId: 'TCH-T2',
    positionTitle: 'ครูผู้สอน',
    department: 'ฝ่ายวิชาการ / ศิลปะและสุขศึกษา',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=T-Teacher2',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },

  // 3. Students / นักเรียนระดับชั้น ชั้นประถมศึกษาปีที่ 1 - ชั้นประถมศึกษาปีที่ 6 (รวม 42 คน)
  // --- ชั้นประถมศึกษาปีที่ 1 ---
  {
    id: 'usr-1209',
    username: '1209',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'พัชระพงศ์',
    lastName: 'กระจกเอี่ยม',
    fullName: 'เด็กชายพัชระพงศ์ กระจกเอี่ยม',
    role: 'student',
    studentId: '1209',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    classRoom: 'ชั้นประถมศึกษาปีที่ 1/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 1',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1209',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1204',
    username: '1204',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'วิภาพร',
    lastName: 'วังวงค์',
    fullName: 'เด็กหญิงวิภาพร วังวงค์',
    role: 'student',
    studentId: '1204',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    classRoom: 'ชั้นประถมศึกษาปีที่ 1/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 1',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1204',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },

  // --- ชั้นประถมศึกษาปีที่ 2 ---
  {
    id: 'usr-1186',
    username: '1186',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธีรวิทย์',
    lastName: 'ทองนันไชย',
    fullName: 'เด็กชายธีรวิทย์ ทองนันไชย',
    role: 'student',
    studentId: '1186',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 2',
    classRoom: 'ชั้นประถมศึกษาปีที่ 2/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 2',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1186',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1200',
    username: '1200',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'วรากร',
    lastName: 'ทองวิชิต',
    fullName: 'เด็กชายวรากร ทองวิชิต',
    role: 'student',
    studentId: '1200',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 2',
    classRoom: 'ชั้นประถมศึกษาปีที่ 2/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 2',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1200',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1231',
    username: '1231',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'สุดพิเศษ',
    lastName: 'เครือศรี',
    fullName: 'เด็กชายสุดพิเศษ เครือศรี',
    role: 'student',
    studentId: '1231',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 2',
    classRoom: 'ชั้นประถมศึกษาปีที่ 2/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 2',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1231',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1241',
    username: '1241',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ปภาวิน',
    lastName: 'แจ่มสว่าง',
    fullName: 'เด็กชายปภาวิน แจ่มสว่าง',
    role: 'student',
    studentId: '1241',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 2',
    classRoom: 'ชั้นประถมศึกษาปีที่ 2/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 2',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1241',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1198',
    username: '1198',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'ขวัญฤทัย',
    lastName: 'ชูสำริด',
    fullName: 'เด็กหญิงขวัญฤทัย ชูสำริด',
    role: 'student',
    studentId: '1198',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 2',
    classRoom: 'ชั้นประถมศึกษาปีที่ 2/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 2',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1198',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1208',
    username: '1208',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'อริยดา',
    lastName: 'แต่งตัว',
    fullName: 'เด็กหญิงอริยดา แต่งตัว',
    role: 'student',
    studentId: '1208',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 2',
    classRoom: 'ชั้นประถมศึกษาปีที่ 2/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 2',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1208',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1211',
    username: '1211',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'อรกัญญา',
    lastName: 'ปลื้มชัยภูมิ',
    fullName: 'เด็กหญิงอรกัญญา ปลื้มชัยภูมิ',
    role: 'student',
    studentId: '1211',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 2',
    classRoom: 'ชั้นประถมศึกษาปีที่ 2/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 2',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1211',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },

  // --- ชั้นประถมศึกษาปีที่ 3 ---
  {
    id: 'usr-1168',
    username: '1168',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ปิยะชัย',
    lastName: 'จิ๋วแหลม',
    fullName: 'เด็กชายปิยะชัย จิ๋วแหลม',
    role: 'student',
    studentId: '1168',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1168',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1183',
    username: '1183',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธวัชชัย',
    lastName: 'แต่งตัว',
    fullName: 'เด็กชายธวัชชัย แต่งตัว',
    role: 'student',
    studentId: '1183',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1183',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1179',
    username: '1179',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ชัยชนะ',
    lastName: 'เหมือนนนท์',
    fullName: 'เด็กชายชัยชนะ เหมือนนนท์',
    role: 'student',
    studentId: '1179',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1179',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1180',
    username: '1180',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ชัยวิชญ์',
    lastName: 'สาลีบุดี',
    fullName: 'เด็กชายชัยวิชญ์ สาลีบุดี',
    role: 'student',
    studentId: '1180',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1180',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1184',
    username: '1184',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธีรภัทร',
    lastName: 'บุตรดี',
    fullName: 'เด็กชายธีรภัทร บุตรดี',
    role: 'student',
    studentId: '1184',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1184',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1182',
    username: '1182',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธนกฤต',
    lastName: 'โตปราง',
    fullName: 'เด็กชายธนกฤต โตปราง',
    role: 'student',
    studentId: '1182',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1182',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1195',
    username: '1195',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ชยกร',
    lastName: 'ครุฑเครือ',
    fullName: 'เด็กชายชยกร ครุฑเครือ',
    role: 'student',
    studentId: '1195',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1195',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1201',
    username: '1201',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'อรรถสิทธิ์',
    lastName: 'ชาววังฆ้อง',
    fullName: 'เด็กชายอรรถสิทธิ์ ชาววังฆ้อง',
    role: 'student',
    studentId: '1201',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1201',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1215',
    username: '1215',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธนวัฒน์',
    lastName: 'ยาหอม',
    fullName: 'เด็กชายธนวัฒน์ ยาหอม',
    role: 'student',
    studentId: '1215',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1215',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1203',
    username: '1203',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'กัญฐิพาพัชญ์',
    lastName: 'อรัญสถิตย์',
    fullName: 'เด็กหญิงกัญฐิพาพัชญ์ อรัญสถิตย์',
    role: 'student',
    studentId: '1203',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    classRoom: 'ชั้นประถมศึกษาปีที่ 3/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 3',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1203',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },

  // --- ชั้นประถมศึกษาปีที่ 4 ---
  {
    id: 'usr-1170',
    username: '1170',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'พงศ์กฤต',
    lastName: 'บุญมั่ง',
    fullName: 'เด็กชายพงศ์กฤต บุญมั่ง',
    role: 'student',
    studentId: '1170',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1170',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1171',
    username: '1171',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธีรเทพ',
    lastName: 'โตปราง',
    fullName: 'เด็กชายธีรเทพ โตปราง',
    role: 'student',
    studentId: '1171',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1171',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1176',
    username: '1176',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'พีรวัตร',
    lastName: 'คงสมทรง',
    fullName: 'เด็กชายพีรวัตร คงสมทรง',
    role: 'student',
    studentId: '1176',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1176',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1177',
    username: '1177',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'สิทธิศักดิ์',
    lastName: 'สังผ่อง',
    fullName: 'เด็กชายสิทธิศักดิ์ สังผ่อง',
    role: 'student',
    studentId: '1177',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1177',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1187',
    username: '1187',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธนาธิป',
    lastName: 'วิการะโพธิ์',
    fullName: 'เด็กชายธนาธิป วิการะโพธิ์',
    role: 'student',
    studentId: '1187',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1187',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1207',
    username: '1207',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'เทวา',
    lastName: 'นามมิตรมาก',
    fullName: 'เด็กชายเทวา นามมิตรมาก',
    role: 'student',
    studentId: '1207',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1207',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1218',
    username: '1218',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'นิติพัฒน์',
    lastName: 'แซ่ซี',
    fullName: 'เด็กชายนิติพัฒน์ แซ่ซี',
    role: 'student',
    studentId: '1218',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1218',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1162',
    username: '1162',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'ณัฏฐ์ชญา',
    lastName: 'สุขน้อย',
    fullName: 'เด็กหญิงณัฏฐ์ชญา สุขน้อย',
    role: 'student',
    studentId: '1162',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1162',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1169',
    username: '1169',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'ร่มเกล้า',
    lastName: 'จันทรา',
    fullName: 'เด็กหญิงร่มเกล้า จันทรา',
    role: 'student',
    studentId: '1169',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 4',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1169',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },

  // --- ชั้นประถมศึกษาปีที่ 5 ---
  {
    id: 'usr-1147',
    username: '1147',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'พัชรพล',
    lastName: 'ทับสงค์',
    fullName: 'เด็กชายพัชรพล ทับสงค์',
    role: 'student',
    studentId: '1147',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1147',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1149',
    username: '1149',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ชยพล',
    lastName: 'รันตเสวก',
    fullName: 'เด็กชายชยพล รันตเสวก',
    role: 'student',
    studentId: '1149',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1149',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1155',
    username: '1155',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ปัญจวิชญ์',
    lastName: 'จักรวาลน้อย',
    fullName: 'เด็กชายปัญจวิชญ์ จักรวาลน้อย',
    role: 'student',
    studentId: '1155',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1155',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1216',
    username: '1216',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธนชิต',
    lastName: 'ยาหอม',
    fullName: 'เด็กชายธนชิต ยาหอม',
    role: 'student',
    studentId: '1216',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1216',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1217',
    username: '1217',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'เทพพิทักษ์',
    lastName: 'คงสิบ',
    fullName: 'เด็กชายเทพพิทักษ์ คงสิบ',
    role: 'student',
    studentId: '1217',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1217',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1150',
    username: '1150',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'เนตรนภา',
    lastName: 'ชาววังฆ้อง',
    fullName: 'เด็กหญิงเนตรนภา ชาววังฆ้อง',
    role: 'student',
    studentId: '1150',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1150',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1161',
    username: '1161',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'กาญจนาภา',
    lastName: 'คุ้มพวก',
    fullName: 'เด็กหญิงกาญจนาภา คุ้มพวก',
    role: 'student',
    studentId: '1161',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1161',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1227',
    username: '1227',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'มาลาทิพย์',
    lastName: 'ต๊ะยามัน',
    fullName: 'เด็กหญิงมาลาทิพย์ ต๊ะยามัน',
    role: 'student',
    studentId: '1227',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1227',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1232',
    username: '1232',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'ฐณัฏฐา',
    lastName: 'สาริทธญาณ์',
    fullName: 'เด็กหญิงฐณัฏฐา สาริทธญาณ์',
    role: 'student',
    studentId: '1232',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 5',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1232',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },

  // --- ชั้นประถมศึกษาปีที่ 6 ---
  {
    id: 'usr-1144',
    username: '1144',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'นเรศ',
    lastName: 'หนูรุ่ง',
    fullName: 'เด็กชายนเรศ หนูรุ่ง',
    role: 'student',
    studentId: '1144',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 6',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1144',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1145',
    username: '1145',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธนาภัทร',
    lastName: 'ชูสำริด',
    fullName: 'เด็กชายธนาภัทร ชูสำริด',
    role: 'student',
    studentId: '1145',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 6',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1145',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1240',
    username: '1240',
    password: '123456',
    titlePrefix: 'เด็กชาย',
    firstName: 'ธนโชติ',
    lastName: 'แซ่เต็น',
    fullName: 'เด็กชายธนโชติ แซ่เต็น',
    role: 'student',
    studentId: '1240',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 6',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1240',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1089',
    username: '1089',
    password: '123456',
    titlePrefix: 'นางสาว',
    firstName: 'ธัญญา',
    lastName: 'กล้าหาญ',
    fullName: 'นางสาวธัญญา กล้าหาญ',
    role: 'student',
    studentId: '1089',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 6',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1089',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'usr-1146',
    username: '1146',
    password: '123456',
    titlePrefix: 'เด็กหญิง',
    firstName: 'วรัญญา',
    lastName: 'ทองคุ่ย',
    fullName: 'เด็กหญิงวรัญญา ทองคุ่ย',
    role: 'student',
    studentId: '1146',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    positionTitle: 'นักเรียนชั้นประถมศึกษาปีที่ 6',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=1146',
    active: true,
    createdAt: '2026-08-01T08:00:00Z',
  },
];

// ==========================================
// Seed Data: Courses across Academic Years
// ==========================================
export const initialCourses: Course[] = [
  // ปีการศึกษา 2568
  {
    id: 'crs-th-p1-2568',
    code: 'ท11101',
    name: 'ภาษาไทย 1 (การอ่านออกเขียนได้)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    subjectGroup: 'ภาษาไทย',
    description: 'เรียนรู้พยัญชนะ สระ วรรณยุกต์ การสะกดคำ และการอ่านเรื่องสั้น',
    teacherId: 'usr-5212',
    teacherName: 'นางสาวจารุณี ทรัพย์สมบูรณ์',
    coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=60',
    academicYear: '2568',
    semester: '1',
    status: 'published',
    enrolledStudentIds: ['usr-1209', 'usr-1204'],
    units: [
      {
        id: 'u-1',
        title: 'หน่วยที่ 1: มาตราตัวสะกดและสระเสียงยาว',
        order: 1,
        lessons: [
          {
            id: 'l-1',
            title: 'บทเรียน: สระเสียงยาว อา อี อู',
            order: 1,
            type: 'text',
            content: 'สระเสียงยาวออกเสียงทอดเสียง เช่น กา ตี ดู',
            completedStudentIds: ['usr-1209', 'usr-1204']
          }
        ]
      }
    ],
    createdAt: '2026-05-15T08:00:00Z',
  },
  {
    id: 'crs-math-p1-2568',
    code: 'ค11101',
    name: 'คณิตศาสตร์ 1 (จำนวนและการบวกลบ)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    subjectGroup: 'คณิตศาสตร์',
    description: 'จำนวนนับ 1 ถึง 100 การบวกและการลบจำนวนไม่เกิน 100',
    teacherId: 'usr-5106',
    teacherName: 'นายกล้านรงค์ ศิรินโรจน์',
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=60',
    academicYear: '2568',
    semester: '1',
    status: 'published',
    enrolledStudentIds: ['usr-1209', 'usr-1204'],
    units: [],
    createdAt: '2026-05-15T08:00:00Z',
  },
  {
    id: 'crs-sci-p3-2568',
    code: 'ว13101',
    name: 'วิทยาศาสตร์และเทคโนโลยี 3',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    subjectGroup: 'วิทยาศาสตร์และเทคโนโลยี',
    description: 'เรียนรู้เรื่องสิ่งมีชีวิต พลังงาน และการใช้วิทยาการคำนวณเบื้องต้น',
    teacherId: 'usr-5106',
    teacherName: 'นายกล้านรงค์ ศิรินโรจน์',
    coverImage: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=60',
    academicYear: '2568',
    semester: '1',
    status: 'published',
    enrolledStudentIds: ['usr-1168', 'usr-1183', 'usr-1179', 'usr-1180', 'usr-1184'],
    units: [],
    createdAt: '2026-05-15T08:00:00Z',
  },
  {
    id: 'crs-eng-p3-2568',
    code: 'อ13101',
    name: 'ภาษาอังกฤษพื้นฐาน 3',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 3',
    subjectGroup: 'ภาษาต่างประเทศ',
    description: 'Basic Phonics, Vocabulary, Daily Conversation for Primary 3',
    teacherId: 'usr-5212',
    teacherName: 'นางสาวจารุณี ทรัพย์สมบูรณ์',
    coverImage: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop&q=60',
    academicYear: '2568',
    semester: '1',
    status: 'published',
    enrolledStudentIds: ['usr-1168', 'usr-1183', 'usr-1179', 'usr-1180', 'usr-1184'],
    units: [],
    createdAt: '2026-05-15T08:00:00Z',
  },
  {
    id: 'crs-sci-p4-2568',
    code: 'ว14101',
    name: 'วิทยาศาสตร์และเทคโนโลยี 4 (สะเต็มศึกษา)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    subjectGroup: 'วิทยาศาสตร์และเทคโนโลยี',
    description: 'เรียนรู้เรื่องกลุ่มสิ่งมีชีวิต พืชและสัตว์ แรงโน้มถ่วง และสะเต็มศึกษา',
    teacherId: 'usr-5106',
    teacherName: 'นายกล้านรงค์ ศิรินโรจน์',
    coverImage: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=800&auto=format&fit=crop&q=60',
    academicYear: '2568',
    semester: '1',
    status: 'published',
    enrolledStudentIds: ['usr-1170', 'usr-1171', 'usr-1176', 'usr-1177', 'usr-1187', 'usr-1207'],
    units: [],
    createdAt: '2026-05-15T08:00:00Z',
  },
  {
    id: 'crs-math-p6-2568',
    code: 'ค16101',
    name: 'คณิตศาสตร์ 6 (เตรียมความพร้อม O-NET)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    subjectGroup: 'คณิตศาสตร์',
    description: 'ห.ร.ม. และ ค.ร.น. เศษส่วน ทศนิยม ร้อยละ รูปเรขาคณิต และสถิติ',
    teacherId: 'usr-5106',
    teacherName: 'นายกล้านรงค์ ศิรินโรจน์',
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&auto=format&fit=crop&q=60',
    academicYear: '2568',
    semester: '1',
    status: 'published',
    enrolledStudentIds: ['usr-1144', 'usr-1145', 'usr-1240', 'usr-1089', 'usr-1146'],
    units: [],
    createdAt: '2026-05-15T08:00:00Z',
  },
  {
    id: 'crs-th-p6-2568',
    code: 'ท16101',
    name: 'ภาษาไทย 6 (การอ่านวิเคราะห์และวรรณคดี)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    subjectGroup: 'ภาษาไทย',
    description: 'การอ่านจับใจความ การเขียนเชิงวิเคราะห์ และวรรณคดีลำนำ',
    teacherId: 'usr-5212',
    teacherName: 'นางสาวจารุณี ทรัพย์สมบูรณ์',
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&auto=format&fit=crop&q=60',
    academicYear: '2568',
    semester: '1',
    status: 'published',
    enrolledStudentIds: ['usr-1144', 'usr-1145', 'usr-1240', 'usr-1089', 'usr-1146'],
    units: [],
    createdAt: '2026-05-15T08:00:00Z',
  },

  // ปีการศึกษา 2567
  {
    id: 'crs-th-p5-2567',
    code: 'ท15101',
    name: 'ภาษาไทย 5 (ปีการศึกษา 2567)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    subjectGroup: 'ภาษาไทย',
    description: 'หลักภาษาและการใช้ภาษาไทย ชั้นประถมศึกษาปีที่ 5',
    teacherId: 'usr-5212',
    teacherName: 'นางสาวจารุณี ทรัพย์สมบูรณ์',
    academicYear: '2567',
    semester: '2',
    status: 'published',
    enrolledStudentIds: ['usr-1144', 'usr-1145', 'usr-1240', 'usr-1089', 'usr-1146'],
    units: [],
    createdAt: '2025-05-15T08:00:00Z',
  },
  {
    id: 'crs-math-p5-2567',
    code: 'ค15101',
    name: 'คณิตศาสตร์ 5 (ปีการศึกษา 2567)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    subjectGroup: 'คณิตศาสตร์',
    description: 'ทศนิยม เศษส่วน ร้อยละ และเรขาคณิต',
    teacherId: 'usr-5106',
    teacherName: 'นายกล้านรงค์ ศิรินโรจน์',
    academicYear: '2567',
    semester: '2',
    status: 'published',
    enrolledStudentIds: ['usr-1144', 'usr-1145', 'usr-1240', 'usr-1089', 'usr-1146'],
    units: [],
    createdAt: '2025-05-15T08:00:00Z',
  },
  {
    id: 'crs-sci-p5-2567',
    code: 'ว15101',
    name: 'วิทยาศาสตร์และเทคโนโลยี 5 (ปีการศึกษา 2567)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    subjectGroup: 'วิทยาศาสตร์และเทคโนโลยี',
    description: 'การเปลี่ยนแปลงของสาร เสียง และการสืบพันธุ์ของพืช',
    teacherId: 'usr-5106',
    teacherName: 'นายกล้านรงค์ ศิรินโรจน์',
    academicYear: '2567',
    semester: '2',
    status: 'published',
    enrolledStudentIds: ['usr-1144', 'usr-1145', 'usr-1240', 'usr-1089', 'usr-1146'],
    units: [],
    createdAt: '2025-05-15T08:00:00Z',
  },

  // ปีการศึกษา 2566
  {
    id: 'crs-th-p4-2566',
    code: 'ท14101',
    name: 'ภาษาไทย 4 (ปีการศึกษา 2566)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    subjectGroup: 'ภาษาไทย',
    description: 'คำนาม คำกริยา คำสรรพนาม และการอ่านบทร้อยกรอง',
    teacherId: 'usr-5212',
    teacherName: 'นางสาวจารุณี ทรัพย์สมบูรณ์',
    academicYear: '2566',
    semester: '2',
    status: 'published',
    enrolledStudentIds: ['usr-1144', 'usr-1145', 'usr-1240', 'usr-1089', 'usr-1146'],
    units: [],
    createdAt: '2024-05-15T08:00:00Z',
  },
  {
    id: 'crs-math-p4-2566',
    code: 'ค14101',
    name: 'คณิตศาสตร์ 4 (ปีการศึกษา 2566)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    subjectGroup: 'คณิตศาสตร์',
    description: 'การบวกลบคูณหารระคน และการวัดพื้นที่',
    teacherId: 'usr-5106',
    teacherName: 'นายกล้านรงค์ ศิรินโรจน์',
    academicYear: '2566',
    semester: '2',
    status: 'published',
    enrolledStudentIds: ['usr-1144', 'usr-1145', 'usr-1240', 'usr-1089', 'usr-1146'],
    units: [],
    createdAt: '2024-05-15T08:00:00Z',
  },
  {
    id: 'crs-sci-p4-2566',
    code: 'ว14101',
    name: 'วิทยาศาสตร์และเทคโนโลยี 4 (ปีการศึกษา 2566)',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    subjectGroup: 'วิทยาศาสตร์และเทคโนโลยี',
    description: 'กลุ่มสิ่งมีชีวิต ดวงจันทร์ และระบบสุริยะ',
    teacherId: 'usr-5106',
    teacherName: 'นายกล้านรงค์ ศิรินโรจน์',
    academicYear: '2566',
    semester: '2',
    status: 'published',
    enrolledStudentIds: ['usr-1144', 'usr-1145', 'usr-1240', 'usr-1089', 'usr-1146'],
    units: [],
    createdAt: '2024-05-15T08:00:00Z',
  }
];

// ==========================================
// Seed Data: Exams across Academic Years
// ==========================================
export const initialExams: Exam[] = [
  // ปี 2568
  {
    id: 'ex-th-p1-2568',
    title: 'แบบทดสอบกลางภาค ภาษาไทย 1 (ท11101)',
    courseId: 'crs-th-p1-2568',
    courseName: 'ภาษาไทย 1 (การอ่านออกเขียนได้)',
    courseCode: 'ท11101',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    academicYear: '2568',
    semester: '1',
    description: 'วัดทักษะการอ่านสะกดคำ สระ และการจำแนกพยัญชนะต้น',
    timeLimitMinutes: 30,
    passingScorePercentage: 60,
    randomizeQuestions: true,
    randomizeChoices: true,
    allowReviewAnswers: true,
    maxAttempts: 2,
    status: 'published',
    totalPoints: 20,
    createdBy: 'usr-5212',
    createdByName: 'นางสาวจารุณี ทรัพย์สมบูรณ์',
    createdAt: '2026-07-10T08:00:00Z',
    questions: [
      {
        id: 'q-th1-1',
        text: 'ข้อใดคือพยัญชนะอักษรกลางทั้งหมด?',
        type: 'choice_single',
        options: ['ก จ ด ต บ ป อ', 'ข ฉ ถ ผ ฝ ส ห', 'ค ง ช ซ ท น พ', 'ง น ม ย ร ล ว'],
        correctAnswer: 0,
        explanation: 'อักษรกลางมี 9 ตัว คือ ไก่ จิก เด็ก ตาย เด็ก ตาย บน ปาก โอ่ง (ก จ ด ต ด ต บ ป อ)',
        points: 4,
        difficulty: 'easy'
      },
      {
        id: 'q-th1-2',
        text: 'คำว่า "บ้าน" ประสมด้วยสระใด?',
        type: 'choice_single',
        options: ['สระ อา', 'สระ อะ', 'สระ อำ', 'สระ เอ'],
        correctAnswer: 0,
        explanation: 'บ + -า + น + ้ = บ้าน (สระ อา)',
        points: 4,
        difficulty: 'easy'
      },
      {
        id: 'q-th1-3',
        text: 'ข้อใดสะกดคำว่า "แม่" ได้ถูกต้อง?',
        type: 'choice_single',
        options: ['มอ - แอ - แม - ไม้เอก - แม่', 'มอ - เอ - เม - ไม้เอก - เม', 'มอ - อา - มา - แม่', 'มอ - โอ - โม - แม่'],
        correctAnswer: 0,
        explanation: 'มอ แอ แม ไม้เอก แม่',
        points: 4,
        difficulty: 'easy'
      },
      {
        id: 'q-th1-4',
        text: 'คำในข้อใดมีความหมายตรงกับรูป "ช้าง"?',
        type: 'choice_single',
        options: ['คชสาร / กุญชร', 'มัสยา', 'ปักษา', 'อาชา'],
        correctAnswer: 0,
        explanation: 'คชสาร และ กุญชร หมายถึง ช้าง',
        points: 4,
        difficulty: 'medium'
      },
      {
        id: 'q-th1-5',
        text: 'ประโยคใดแสดงการกระทำที่สมบูรณ์?',
        type: 'choice_single',
        options: ['น้องดื่มนมรสหวาน', 'บ้านสวยงามหลังใหญ่', 'ต้นไม้เขียวขจีในสวน', 'ท้องฟ้าแจ่มใสวันนี้'],
        correctAnswer: 0,
        explanation: 'น้อง (ประธาน) + ดื่ม (กริยา) + นมรสหวาน (กรรม)',
        points: 4,
        difficulty: 'medium'
      }
    ]
  },
  {
    id: 'ex-math-p1-2568',
    title: 'แบบทดสอบกลางภาค คณิตศาสตร์ 1 (ค11101)',
    courseId: 'crs-math-p1-2568',
    courseName: 'คณิตศาสตร์ 1 (จำนวนและการบวกลบ)',
    courseCode: 'ค11101',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    academicYear: '2568',
    semester: '1',
    description: 'การบวก ลบ จำนวนนับ 1 ถึง 20 และการแก้โจทย์ปัญหาภาพ',
    timeLimitMinutes: 30,
    passingScorePercentage: 60,
    randomizeQuestions: true,
    randomizeChoices: true,
    allowReviewAnswers: true,
    maxAttempts: 2,
    status: 'published',
    totalPoints: 20,
    createdBy: 'usr-5106',
    createdByName: 'นายกล้านรงค์ ศิรินโรจน์',
    createdAt: '2026-07-12T08:00:00Z',
    questions: [
      {
        id: 'q-m1-1',
        text: 'ผลลัพธ์ของ 8 + 7 เท่ากับเท่าใด?',
        type: 'choice_single',
        options: ['15', '14', '16', '13'],
        correctAnswer: 0,
        explanation: '8 + 7 = 15',
        points: 5,
        difficulty: 'easy'
      },
      {
        id: 'q-m1-2',
        text: 'มีแอปเปิ้ล 18 ผล รับประทานไป 6 ผล เหลือแอปเปิ้ลกี่ผล?',
        type: 'choice_single',
        options: ['12 ผล', '14 ผล', '10 ผล', '13 ผล'],
        correctAnswer: 0,
        explanation: '18 - 6 = 12 ผล',
        points: 5,
        difficulty: 'easy'
      },
      {
        id: 'q-m1-3',
        text: 'จำนวนใดมีค่ามากกว่า 15 แต่น้อยกว่า 17?',
        type: 'choice_single',
        options: ['16', '14', '18', '15'],
        correctAnswer: 0,
        explanation: '16 อยู่ระหว่าง 15 และ 17',
        points: 5,
        difficulty: 'easy'
      },
      {
        id: 'q-m1-4',
        text: 'ข้อใดถูกต้อง?',
        type: 'choice_single',
        options: ['9 + 6 = 15', '7 + 8 = 14', '12 - 5 = 6', '19 - 8 = 10'],
        correctAnswer: 0,
        explanation: '9 + 6 = 15 ถูกต้อง',
        points: 5,
        difficulty: 'easy'
      }
    ]
  },
  {
    id: 'ex-sci-p4-2568',
    title: 'แบบทดสอบกลางภาค วิทยาศาสตร์และเทคโนโลยี 4 (ว14101)',
    courseId: 'crs-sci-p4-2568',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 4 (สะเต็มศึกษา)',
    courseCode: 'ว14101',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    academicYear: '2568',
    semester: '1',
    description: 'การจำแนกพืชและสัตว์ สสาร มวล และแรงโน้มถ่วงของโลก',
    timeLimitMinutes: 40,
    passingScorePercentage: 60,
    randomizeQuestions: true,
    randomizeChoices: true,
    allowReviewAnswers: true,
    maxAttempts: 2,
    status: 'published',
    totalPoints: 20,
    createdBy: 'usr-5106',
    createdByName: 'นายกล้านรงค์ ศิรินโรจน์',
    createdAt: '2026-07-15T08:00:00Z',
    questions: [
      {
        id: 'q-s4-1',
        text: 'ข้อใดจัดเป็นสัตว์มีกระดูกสันหลังกลุ่มสัตว์สะเทินน้ำสะเทินบก?',
        type: 'choice_single',
        options: ['กบ ปาด อึ่งอ่าง', 'จระเข้ เต่า กิ้งก่า', 'ปลาช่อน ปลาดุก ปลากระพง', 'นกกระจอก ไก่ เป็ด'],
        correctAnswer: 0,
        explanation: 'กบ ปาด อึ่งอ่าง เป็นสัตว์สะเทินน้ำสะเทินบก',
        points: 5,
        difficulty: 'medium'
      },
      {
        id: 'q-s4-2',
        text: 'ส่วนประกอบใดของพืชทำหน้าที่สังเคราะห์ด้วยแสงเป็นหลัก?',
        type: 'choice_single',
        options: ['ใบ (มีคลอโรฟิลล์)', 'ราก', 'ลำต้น', 'ผลและเมล็ด'],
        correctAnswer: 0,
        explanation: 'ใบมีคลอโรพลาสต์และคลอโรฟิลล์ทำหน้าที่สร้างอาหารด้วยการสังเคราะห์ด้วยแสง',
        points: 5,
        difficulty: 'easy'
      },
      {
        id: 'q-s4-3',
        text: 'แรงดึงดูดที่โลกกระทำต่อมวลของวัตถุเรียกว่าอะไร?',
        type: 'choice_single',
        options: ['น้ำหนัก (Weight)', 'มวลสาร (Mass)', 'แรงเสียดทาน (Friction)', 'แรงแม่เหล็ก (Magnetism)'],
        correctAnswer: 0,
        explanation: 'น้ำหนักคือกำลังของแรงโน้มถ่วงโลกที่กระทำต่อมวล',
        points: 5,
        difficulty: 'medium'
      },
      {
        id: 'q-s4-4',
        text: 'วัตถุในข้อใดมีสมบัติเป็นตัวนำไฟฟ้าที่ดีที่สุด?',
        type: 'choice_single',
        options: ['ลวดทองแดง', 'แท่งแก้ว', 'ยางลบ', 'ไม้บรรทัดพลาสติก'],
        correctAnswer: 0,
        explanation: 'ทองแดงเป็นโลหะที่มีอิเล็กตรอนอิสระนำไฟฟ้าได้ดีเยี่ยม',
        points: 5,
        difficulty: 'easy'
      }
    ]
  },
  {
    id: 'ex-math-p6-2568',
    title: 'แบบทดสอบเตรียมความพร้อม O-NET คณิตศาสตร์ 6 (ค16101)',
    courseId: 'crs-math-p6-2568',
    courseName: 'คณิตศาสตร์ 6 (เตรียมความพร้อม O-NET)',
    courseCode: 'ค16101',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    academicYear: '2568',
    semester: '1',
    description: 'การหา ห.ร.ม. ค.ร.น. เศษส่วน และการแก้โจทย์ปัญหาเชิงซ้อน',
    timeLimitMinutes: 45,
    passingScorePercentage: 60,
    randomizeQuestions: true,
    randomizeChoices: true,
    allowReviewAnswers: true,
    maxAttempts: 2,
    status: 'published',
    totalPoints: 20,
    createdBy: 'usr-5106',
    createdByName: 'นายกล้านรงค์ ศิรินโรจน์',
    createdAt: '2026-07-20T08:00:00Z',
    questions: [
      {
        id: 'q-m6-1',
        text: 'ห.ร.ม. ของ 24, 36 และ 48 มีค่าเท่ากับข้อใด?',
        type: 'choice_single',
        options: ['12', '6', '24', '144'],
        correctAnswer: 0,
        explanation: 'ตัวหารร่วมมากที่สุดของ 24, 36, 48 คือ 12',
        points: 5,
        difficulty: 'medium'
      },
      {
        id: 'q-m6-2',
        text: 'ค.ร.น. ของ 6, 8 และ 12 มีค่าเท่าใด?',
        type: 'choice_single',
        options: ['24', '48', '12', '72'],
        correctAnswer: 0,
        explanation: 'ค.ร.น. ของ 6, 8, 12 คือ 24',
        points: 5,
        difficulty: 'medium'
      },
      {
        id: 'q-m6-3',
        text: 'ซื้อสินค้าราคา 1,200 บาท ได้รับส่วนลด 15% จะต้องจ่ายเงินกี่บาท?',
        type: 'choice_single',
        options: ['1,020 บาท', '1,050 บาท', '980 บาท', '1,000 บาท'],
        correctAnswer: 0,
        explanation: 'ส่วนลด = 1,200 x 0.15 = 180 บาท -> จ่าย = 1,200 - 180 = 1,020 บาท',
        points: 5,
        difficulty: 'medium'
      },
      {
        id: 'q-m6-4',
        text: 'พื้นที่ของรูปสามเหลี่ยมที่มีฐานยาว 14 ซม. และสูง 8 ซม. คือเท่าใด?',
        type: 'choice_single',
        options: ['56 ตร.ซม.', '112 ตร.ซม.', '48 ตร.ซม.', '22 ตร.ซม.'],
        correctAnswer: 0,
        explanation: 'พื้นที่สามเหลี่ยม = 1/2 x ฐาน x สูง = 1/2 x 14 x 8 = 56 ตร.ซม.',
        points: 5,
        difficulty: 'easy'
      }
    ]
  },

  // ปี 2567
  {
    id: 'ex-math-p5-2567',
    title: 'แบบทดสอบปลายภาค คณิตศาสตร์ 5 (ปีการศึกษา 2567)',
    courseId: 'crs-math-p5-2567',
    courseName: 'คณิตศาสตร์ 5 (ปีการศึกษา 2567)',
    courseCode: 'ค15101',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    academicYear: '2567',
    semester: '2',
    description: 'การคูณหารเศษส่วน ร้อยละ และรูปเรขาคณิตสามมิติ',
    timeLimitMinutes: 40,
    passingScorePercentage: 60,
    randomizeQuestions: true,
    randomizeChoices: true,
    allowReviewAnswers: true,
    maxAttempts: 2,
    status: 'published',
    totalPoints: 20,
    createdBy: 'usr-5106',
    createdByName: 'นายกล้านรงค์ ศิรินโรจน์',
    createdAt: '2025-10-15T08:00:00Z',
    questions: [
      {
        id: 'q-m5-1',
        text: '3/4 + 1/2 มีค่าเท่ากับเท่าใด?',
        type: 'choice_single',
        options: ['1 1/4 (5/4)', '4/6 (2/3)', '4/4 (1)', '7/8'],
        correctAnswer: 0,
        explanation: '3/4 + 2/4 = 5/4 = 1 1/4',
        points: 10,
        difficulty: 'easy'
      },
      {
        id: 'q-m5-2',
        text: 'ร้อยละ 40 ของ 500 มีค่าเท่ากับเท่าใด?',
        type: 'choice_single',
        options: ['200', '250', '150', '300'],
        correctAnswer: 0,
        explanation: '40/100 x 500 = 200',
        points: 10,
        difficulty: 'easy'
      }
    ]
  },
  {
    id: 'ex-sci-p5-2567',
    title: 'แบบทดสอบปลายภาค วิทยาศาสตร์ 5 (ปีการศึกษา 2567)',
    courseId: 'crs-sci-p5-2567',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 5 (ปีการศึกษา 2567)',
    courseCode: 'ว15101',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    academicYear: '2567',
    semester: '2',
    description: 'แรงเสียดทานและเสียงกับการได้ยิน',
    timeLimitMinutes: 40,
    passingScorePercentage: 60,
    randomizeQuestions: true,
    randomizeChoices: true,
    allowReviewAnswers: true,
    maxAttempts: 2,
    status: 'published',
    totalPoints: 20,
    createdBy: 'usr-5106',
    createdByName: 'นายกล้านรงค์ ศิรินโรจน์',
    createdAt: '2025-10-18T08:00:00Z',
    questions: [
      {
        id: 'q-s5-1',
        text: 'เสียงเดินทางผ่านตัวกลางชนิดใดได้เร็วที่สุด?',
        type: 'choice_single',
        options: ['ของแข็ง', 'ของเหลว', 'ก๊าซ', 'สุญญากาศ'],
        correctAnswer: 0,
        explanation: 'โมเลกุลของแข็งอยู่ชิดกันมากที่สุดทำให้ส่งต่อพลังงานเสียงได้เร็วที่สุด',
        points: 10,
        difficulty: 'medium'
      },
      {
        id: 'q-s5-2',
        text: 'ข้อใดเป็นการลดแรงเสียดทานที่เป็นประโยชน์?',
        type: 'choice_single',
        options: ['การหยอดน้ำมันหล่อลื่นในเครื่องยนต์', 'การเพิ่มดอกยางรถยนต์', 'การใช้รองเท้าสตั๊ดมีปุ่ม', 'การทำพื้นผิวบันไดให้หยาบ'],
        correctAnswer: 0,
        explanation: 'น้ำมันหล่อลื่นช่วยลดการเสียดสีและการสึกหรอของเครื่องยนต์',
        points: 10,
        difficulty: 'easy'
      }
    ]
  },

  // ปี 2566
  {
    id: 'ex-math-p4-2566',
    title: 'แบบทดสอบปลายภาค คณิตศาสตร์ 4 (ปีการศึกษา 2566)',
    courseId: 'crs-math-p4-2566',
    courseName: 'คณิตศาสตร์ 4 (ปีการศึกษา 2566)',
    courseCode: 'ค14101',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    academicYear: '2566',
    semester: '2',
    description: 'การบวกลบคูณหารระคนและเวลา',
    timeLimitMinutes: 40,
    passingScorePercentage: 60,
    randomizeQuestions: true,
    randomizeChoices: true,
    allowReviewAnswers: true,
    maxAttempts: 2,
    status: 'published',
    totalPoints: 20,
    createdBy: 'usr-5106',
    createdByName: 'นายกล้านรงค์ ศิรินโรจน์',
    createdAt: '2024-10-15T08:00:00Z',
    questions: [
      {
        id: 'q-m4-1',
        text: '(25 x 4) + (150 / 3) มีค่าเท่ากับเท่าใด?',
        type: 'choice_single',
        options: ['150', '140', '160', '130'],
        correctAnswer: 0,
        explanation: '100 + 50 = 150',
        points: 10,
        difficulty: 'easy'
      },
      {
        id: 'q-m4-2',
        text: 'เวลา 2 ชั่วโมง 45 นาที คิดเป็นกี่นาที?',
        type: 'choice_single',
        options: ['165 นาที', '145 นาที', '180 นาที', '150 นาที'],
        correctAnswer: 0,
        explanation: '(2 x 60) + 45 = 120 + 45 = 165 นาที',
        points: 10,
        difficulty: 'easy'
      }
    ]
  },
  {
    id: 'ex-sci-p4-2566',
    title: 'แบบทดสอบปลายภาค วิทยาศาสตร์ 4 (ปีการศึกษา 2566)',
    courseId: 'crs-sci-p4-2566',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 4 (ปีการศึกษา 2566)',
    courseCode: 'ว14101',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    academicYear: '2566',
    semester: '2',
    description: 'ดวงจันทร์และระบบสุริยะ',
    timeLimitMinutes: 40,
    passingScorePercentage: 60,
    randomizeQuestions: true,
    randomizeChoices: true,
    allowReviewAnswers: true,
    maxAttempts: 2,
    status: 'published',
    totalPoints: 20,
    createdBy: 'usr-5106',
    createdByName: 'นายกล้านรงค์ ศิรินโรจน์',
    createdAt: '2024-10-18T08:00:00Z',
    questions: [
      {
        id: 'q-s4-66-1',
        text: 'ดาวเคราะห์ดวงใดอยู่ใกล้ดวงอาทิตย์มากที่สุดในระบบสุริยะ?',
        type: 'choice_single',
        options: ['ดาวพุธ (Mercury)', 'ดาวศุกร์ (Venus)', 'โลก (Earth)', 'ดาวอังคาร (Mars)'],
        correctAnswer: 0,
        explanation: 'ดาวพุธเป็นดาวเคราะห์ลำดับที่ 1 ที่อยู่ใกล้ดวงอาทิตย์ที่สุด',
        points: 10,
        difficulty: 'easy'
      },
      {
        id: 'q-s4-66-2',
        text: 'ปรากฏการณ์ข้างขึ้นข้างแรมเกิดจากการโคจรของสิ่งใด?',
        type: 'choice_single',
        options: ['ดวงจันทร์โคจรรอบโลก', 'โลกโคจรรอบดวงอาทิตย์', 'โลกหมุนรอบตัวเอง', 'ดวงอาทิตย์หมุนรอบตัวเอง'],
        correctAnswer: 0,
        explanation: 'ดวงจันทร์โคจรรอบโลกทำให้มุมรับแสงจากดวงอาทิตย์เปลี่ยนแปลงไปเมื่อมองจากโลก',
        points: 10,
        difficulty: 'medium'
      }
    ]
  }
];

// ==========================================
// Seed Data: Exam Submissions across Academic Years
// (Generated systematically for students across 2566, 2567, 2568)
// ==========================================
export const initialSubmissions: ExamSubmission[] = [
  // ----------------------------------------
  // ปีการศึกษา 2568 (ชั้น ป.1, ป.4, ป.6)
  // ----------------------------------------
  // ป.1 ภาษาไทย 2568
  {
    id: 'sub-68-1209-th',
    examId: 'ex-th-p1-2568',
    examTitle: 'แบบทดสอบกลางภาค ภาษาไทย 1 (ท11101)',
    courseId: 'crs-th-p1-2568',
    courseName: 'ภาษาไทย 1 (การอ่านออกเขียนได้)',
    courseCode: 'ท11101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1209',
    studentName: 'เด็กชายพัชระพงศ์ กระจกเอี่ยม',
    studentCode: '1209',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    classRoom: 'ชั้นประถมศึกษาปีที่ 1/1',
    answers: { 'q-th1-1': 0, 'q-th1-2': 0, 'q-th1-3': 0, 'q-th1-4': 0, 'q-th1-5': 0 },
    itemResults: {
      'q-th1-1': { isCorrect: true, points: 4 },
      'q-th1-2': { isCorrect: true, points: 4 },
      'q-th1-3': { isCorrect: true, points: 4 },
      'q-th1-4': { isCorrect: true, points: 4 },
      'q-th1-5': { isCorrect: true, points: 4 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2026-07-25T09:00:00Z',
    submittedAt: '2026-07-25T09:18:00Z',
    timeSpentSeconds: 1080,
    attemptNumber: 1
  },
  {
    id: 'sub-68-1204-th',
    examId: 'ex-th-p1-2568',
    examTitle: 'แบบทดสอบกลางภาค ภาษาไทย 1 (ท11101)',
    courseId: 'crs-th-p1-2568',
    courseName: 'ภาษาไทย 1 (การอ่านออกเขียนได้)',
    courseCode: 'ท11101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1204',
    studentName: 'เด็กหญิงวิภาพร วังวงค์',
    studentCode: '1204',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    classRoom: 'ชั้นประถมศึกษาปีที่ 1/1',
    answers: { 'q-th1-1': 0, 'q-th1-2': 0, 'q-th1-3': 0, 'q-th1-4': 1, 'q-th1-5': 0 },
    itemResults: {
      'q-th1-1': { isCorrect: true, points: 4 },
      'q-th1-2': { isCorrect: true, points: 4 },
      'q-th1-3': { isCorrect: true, points: 4 },
      'q-th1-4': { isCorrect: false, points: 0 },
      'q-th1-5': { isCorrect: true, points: 4 }
    },
    score: 16,
    totalPoints: 20,
    percentage: 80,
    passed: true,
    startedAt: '2026-07-25T09:00:00Z',
    submittedAt: '2026-07-25T09:20:00Z',
    timeSpentSeconds: 1200,
    attemptNumber: 1
  },
  // ป.1 คณิตศาสตร์ 2568
  {
    id: 'sub-68-1209-m',
    examId: 'ex-math-p1-2568',
    examTitle: 'แบบทดสอบกลางภาค คณิตศาสตร์ 1 (ค11101)',
    courseId: 'crs-math-p1-2568',
    courseName: 'คณิตศาสตร์ 1 (จำนวนและการบวกลบ)',
    courseCode: 'ค11101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1209',
    studentName: 'เด็กชายพัชระพงศ์ กระจกเอี่ยม',
    studentCode: '1209',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    classRoom: 'ชั้นประถมศึกษาปีที่ 1/1',
    answers: { 'q-m1-1': 0, 'q-m1-2': 0, 'q-m1-3': 0, 'q-m1-4': 0 },
    itemResults: {
      'q-m1-1': { isCorrect: true, points: 5 },
      'q-m1-2': { isCorrect: true, points: 5 },
      'q-m1-3': { isCorrect: true, points: 5 },
      'q-m1-4': { isCorrect: true, points: 5 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2026-07-26T10:00:00Z',
    submittedAt: '2026-07-26T10:15:00Z',
    timeSpentSeconds: 900,
    attemptNumber: 1
  },
  {
    id: 'sub-68-1204-m',
    examId: 'ex-math-p1-2568',
    examTitle: 'แบบทดสอบกลางภาค คณิตศาสตร์ 1 (ค11101)',
    courseId: 'crs-math-p1-2568',
    courseName: 'คณิตศาสตร์ 1 (จำนวนและการบวกลบ)',
    courseCode: 'ค11101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1204',
    studentName: 'เด็กหญิงวิภาพร วังวงค์',
    studentCode: '1204',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 1',
    classRoom: 'ชั้นประถมศึกษาปีที่ 1/1',
    answers: { 'q-m1-1': 0, 'q-m1-2': 0, 'q-m1-3': 1, 'q-m1-4': 0 },
    itemResults: {
      'q-m1-1': { isCorrect: true, points: 5 },
      'q-m1-2': { isCorrect: true, points: 5 },
      'q-m1-3': { isCorrect: false, points: 0 },
      'q-m1-4': { isCorrect: true, points: 5 }
    },
    score: 15,
    totalPoints: 20,
    percentage: 75,
    passed: true,
    startedAt: '2026-07-26T10:00:00Z',
    submittedAt: '2026-07-26T10:19:00Z',
    timeSpentSeconds: 1140,
    attemptNumber: 1
  },

  // ป.4 วิทยาศาสตร์ 2568
  {
    id: 'sub-68-1170-sci',
    examId: 'ex-sci-p4-2568',
    examTitle: 'แบบทดสอบกลางภาค วิทยาศาสตร์และเทคโนโลยี 4 (ว14101)',
    courseId: 'crs-sci-p4-2568',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 4 (สะเต็มศึกษา)',
    courseCode: 'ว14101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1170',
    studentName: 'เด็กชายพงศ์กฤต บุญมั่ง',
    studentCode: '1170',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    answers: { 'q-s4-1': 0, 'q-s4-2': 0, 'q-s4-3': 0, 'q-s4-4': 0 },
    itemResults: {
      'q-s4-1': { isCorrect: true, points: 5 },
      'q-s4-2': { isCorrect: true, points: 5 },
      'q-s4-3': { isCorrect: true, points: 5 },
      'q-s4-4': { isCorrect: true, points: 5 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2026-07-28T09:00:00Z',
    submittedAt: '2026-07-28T09:25:00Z',
    timeSpentSeconds: 1500,
    attemptNumber: 1
  },
  {
    id: 'sub-68-1171-sci',
    examId: 'ex-sci-p4-2568',
    examTitle: 'แบบทดสอบกลางภาค วิทยาศาสตร์และเทคโนโลยี 4 (ว14101)',
    courseId: 'crs-sci-p4-2568',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 4 (สะเต็มศึกษา)',
    courseCode: 'ว14101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1171',
    studentName: 'เด็กชายธีรเทพ โตปราง',
    studentCode: '1171',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    answers: { 'q-s4-1': 0, 'q-s4-2': 0, 'q-s4-3': 1, 'q-s4-4': 0 },
    itemResults: {
      'q-s4-1': { isCorrect: true, points: 5 },
      'q-s4-2': { isCorrect: true, points: 5 },
      'q-s4-3': { isCorrect: false, points: 0 },
      'q-s4-4': { isCorrect: true, points: 5 }
    },
    score: 15,
    totalPoints: 20,
    percentage: 75,
    passed: true,
    startedAt: '2026-07-28T09:00:00Z',
    submittedAt: '2026-07-28T09:28:00Z',
    timeSpentSeconds: 1680,
    attemptNumber: 1
  },
  {
    id: 'sub-68-1176-sci',
    examId: 'ex-sci-p4-2568',
    examTitle: 'แบบทดสอบกลางภาค วิทยาศาสตร์และเทคโนโลยี 4 (ว14101)',
    courseId: 'crs-sci-p4-2568',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 4 (สะเต็มศึกษา)',
    courseCode: 'ว14101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1176',
    studentName: 'เด็กชายพีรวัตร คงสมทรง',
    studentCode: '1176',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    answers: { 'q-s4-1': 0, 'q-s4-2': 0, 'q-s4-3': 0, 'q-s4-4': 0 },
    itemResults: {
      'q-s4-1': { isCorrect: true, points: 5 },
      'q-s4-2': { isCorrect: true, points: 5 },
      'q-s4-3': { isCorrect: true, points: 5 },
      'q-s4-4': { isCorrect: true, points: 5 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2026-07-28T09:00:00Z',
    submittedAt: '2026-07-28T09:21:00Z',
    timeSpentSeconds: 1260,
    attemptNumber: 1
  },

  // ป.6 คณิตศาสตร์ 2568
  {
    id: 'sub-68-1144-m6',
    examId: 'ex-math-p6-2568',
    examTitle: 'แบบทดสอบเตรียมความพร้อม O-NET คณิตศาสตร์ 6 (ค16101)',
    courseId: 'crs-math-p6-2568',
    courseName: 'คณิตศาสตร์ 6 (เตรียมความพร้อม O-NET)',
    courseCode: 'ค16101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1144',
    studentName: 'เด็กชายนเรศ หนูรุ่ง',
    studentCode: '1144',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    answers: { 'q-m6-1': 0, 'q-m6-2': 0, 'q-m6-3': 0, 'q-m6-4': 0 },
    itemResults: {
      'q-m6-1': { isCorrect: true, points: 5 },
      'q-m6-2': { isCorrect: true, points: 5 },
      'q-m6-3': { isCorrect: true, points: 5 },
      'q-m6-4': { isCorrect: true, points: 5 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2026-07-30T10:00:00Z',
    submittedAt: '2026-07-30T10:30:00Z',
    timeSpentSeconds: 1800,
    attemptNumber: 1
  },
  {
    id: 'sub-68-1145-m6',
    examId: 'ex-math-p6-2568',
    examTitle: 'แบบทดสอบเตรียมความพร้อม O-NET คณิตศาสตร์ 6 (ค16101)',
    courseId: 'crs-math-p6-2568',
    courseName: 'คณิตศาสตร์ 6 (เตรียมความพร้อม O-NET)',
    courseCode: 'ค16101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1145',
    studentName: 'เด็กชายธนาภัทร ชูสำริด',
    studentCode: '1145',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    answers: { 'q-m6-1': 0, 'q-m6-2': 0, 'q-m6-3': 1, 'q-m6-4': 0 },
    itemResults: {
      'q-m6-1': { isCorrect: true, points: 5 },
      'q-m6-2': { isCorrect: true, points: 5 },
      'q-m6-3': { isCorrect: false, points: 0 },
      'q-m6-4': { isCorrect: true, points: 5 }
    },
    score: 15,
    totalPoints: 20,
    percentage: 75,
    passed: true,
    startedAt: '2026-07-30T10:00:00Z',
    submittedAt: '2026-07-30T10:32:00Z',
    timeSpentSeconds: 1920,
    attemptNumber: 1
  },
  {
    id: 'sub-68-1240-m6',
    examId: 'ex-math-p6-2568',
    examTitle: 'แบบทดสอบเตรียมความพร้อม O-NET คณิตศาสตร์ 6 (ค16101)',
    courseId: 'crs-math-p6-2568',
    courseName: 'คณิตศาสตร์ 6 (เตรียมความพร้อม O-NET)',
    courseCode: 'ค16101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1240',
    studentName: 'เด็กชายธนโชติ แซ่เต็น',
    studentCode: '1240',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    answers: { 'q-m6-1': 0, 'q-m6-2': 0, 'q-m6-3': 0, 'q-m6-4': 0 },
    itemResults: {
      'q-m6-1': { isCorrect: true, points: 5 },
      'q-m6-2': { isCorrect: true, points: 5 },
      'q-m6-3': { isCorrect: true, points: 5 },
      'q-m6-4': { isCorrect: true, points: 5 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2026-07-30T10:00:00Z',
    submittedAt: '2026-07-30T10:28:00Z',
    timeSpentSeconds: 1680,
    attemptNumber: 1
  },
  {
    id: 'sub-68-1089-m6',
    examId: 'ex-math-p6-2568',
    examTitle: 'แบบทดสอบเตรียมความพร้อม O-NET คณิตศาสตร์ 6 (ค16101)',
    courseId: 'crs-math-p6-2568',
    courseName: 'คณิตศาสตร์ 6 (เตรียมความพร้อม O-NET)',
    courseCode: 'ค16101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1089',
    studentName: 'นางสาวธัญญา กล้าหาญ',
    studentCode: '1089',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    answers: { 'q-m6-1': 0, 'q-m6-2': 0, 'q-m6-3': 0, 'q-m6-4': 0 },
    itemResults: {
      'q-m6-1': { isCorrect: true, points: 5 },
      'q-m6-2': { isCorrect: true, points: 5 },
      'q-m6-3': { isCorrect: true, points: 5 },
      'q-m6-4': { isCorrect: true, points: 5 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2026-07-30T10:00:00Z',
    submittedAt: '2026-07-30T10:24:00Z',
    timeSpentSeconds: 1440,
    attemptNumber: 1
  },
  {
    id: 'sub-68-1146-m6',
    examId: 'ex-math-p6-2568',
    examTitle: 'แบบทดสอบเตรียมความพร้อม O-NET คณิตศาสตร์ 6 (ค16101)',
    courseId: 'crs-math-p6-2568',
    courseName: 'คณิตศาสตร์ 6 (เตรียมความพร้อม O-NET)',
    courseCode: 'ค16101',
    academicYear: '2568',
    semester: '1',
    studentId: 'usr-1146',
    studentName: 'เด็กหญิงวรัญญา ทองคุ่ย',
    studentCode: '1146',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 6',
    classRoom: 'ชั้นประถมศึกษาปีที่ 6/1',
    answers: { 'q-m6-1': 0, 'q-m6-2': 1, 'q-m6-3': 0, 'q-m6-4': 0 },
    itemResults: {
      'q-m6-1': { isCorrect: true, points: 5 },
      'q-m6-2': { isCorrect: false, points: 0 },
      'q-m6-3': { isCorrect: true, points: 5 },
      'q-m6-4': { isCorrect: true, points: 5 }
    },
    score: 15,
    totalPoints: 20,
    percentage: 75,
    passed: true,
    startedAt: '2026-07-30T10:00:00Z',
    submittedAt: '2026-07-30T10:35:00Z',
    timeSpentSeconds: 2100,
    attemptNumber: 1
  },

  // ----------------------------------------
  // ปีการศึกษา 2567 (ชั้น ป.5 ในอดีต)
  // ----------------------------------------
  {
    id: 'sub-67-1144-m5',
    examId: 'ex-math-p5-2567',
    examTitle: 'แบบทดสอบปลายภาค คณิตศาสตร์ 5 (ปีการศึกษา 2567)',
    courseId: 'crs-math-p5-2567',
    courseName: 'คณิตศาสตร์ 5 (ปีการศึกษา 2567)',
    courseCode: 'ค15101',
    academicYear: '2567',
    semester: '2',
    studentId: 'usr-1144',
    studentName: 'เด็กชายนเรศ หนูรุ่ง',
    studentCode: '1144',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    answers: { 'q-m5-1': 0, 'q-m5-2': 0 },
    itemResults: {
      'q-m5-1': { isCorrect: true, points: 10 },
      'q-m5-2': { isCorrect: true, points: 10 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2025-10-20T09:00:00Z',
    submittedAt: '2025-10-20T09:20:00Z',
    timeSpentSeconds: 1200,
    attemptNumber: 1
  },
  {
    id: 'sub-67-1145-m5',
    examId: 'ex-math-p5-2567',
    examTitle: 'แบบทดสอบปลายภาค คณิตศาสตร์ 5 (ปีการศึกษา 2567)',
    courseId: 'crs-math-p5-2567',
    courseName: 'คณิตศาสตร์ 5 (ปีการศึกษา 2567)',
    courseCode: 'ค15101',
    academicYear: '2567',
    semester: '2',
    studentId: 'usr-1145',
    studentName: 'เด็กชายธนาภัทร ชูสำริด',
    studentCode: '1145',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    answers: { 'q-m5-1': 0, 'q-m5-2': 1 },
    itemResults: {
      'q-m5-1': { isCorrect: true, points: 10 },
      'q-m5-2': { isCorrect: false, points: 0 }
    },
    score: 10,
    totalPoints: 20,
    percentage: 50,
    passed: false,
    startedAt: '2025-10-20T09:00:00Z',
    submittedAt: '2025-10-20T09:25:00Z',
    timeSpentSeconds: 1500,
    attemptNumber: 1
  },
  {
    id: 'sub-67-1144-s5',
    examId: 'ex-sci-p5-2567',
    examTitle: 'แบบทดสอบปลายภาค วิทยาศาสตร์ 5 (ปีการศึกษา 2567)',
    courseId: 'crs-sci-p5-2567',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 5 (ปีการศึกษา 2567)',
    courseCode: 'ว15101',
    academicYear: '2567',
    semester: '2',
    studentId: 'usr-1144',
    studentName: 'เด็กชายนเรศ หนูรุ่ง',
    studentCode: '1144',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    answers: { 'q-s5-1': 0, 'q-s5-2': 0 },
    itemResults: {
      'q-s5-1': { isCorrect: true, points: 10 },
      'q-s5-2': { isCorrect: true, points: 10 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2025-10-22T09:00:00Z',
    submittedAt: '2025-10-22T09:18:00Z',
    timeSpentSeconds: 1080,
    attemptNumber: 1
  },
  {
    id: 'sub-67-1089-s5',
    examId: 'ex-sci-p5-2567',
    examTitle: 'แบบทดสอบปลายภาค วิทยาศาสตร์ 5 (ปีการศึกษา 2567)',
    courseId: 'crs-sci-p5-2567',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 5 (ปีการศึกษา 2567)',
    courseCode: 'ว15101',
    academicYear: '2567',
    semester: '2',
    studentId: 'usr-1089',
    studentName: 'นางสาวธัญญา กล้าหาญ',
    studentCode: '1089',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 5',
    classRoom: 'ชั้นประถมศึกษาปีที่ 5/1',
    answers: { 'q-s5-1': 0, 'q-s5-2': 0 },
    itemResults: {
      'q-s5-1': { isCorrect: true, points: 10 },
      'q-s5-2': { isCorrect: true, points: 10 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2025-10-22T09:00:00Z',
    submittedAt: '2025-10-22T09:15:00Z',
    timeSpentSeconds: 900,
    attemptNumber: 1
  },

  // ----------------------------------------
  // ปีการศึกษา 2566 (ชั้น ป.4 ในอดีต)
  // ----------------------------------------
  {
    id: 'sub-66-1144-m4',
    examId: 'ex-math-p4-2566',
    examTitle: 'แบบทดสอบปลายภาค คณิตศาสตร์ 4 (ปีการศึกษา 2566)',
    courseId: 'crs-math-p4-2566',
    courseName: 'คณิตศาสตร์ 4 (ปีการศึกษา 2566)',
    courseCode: 'ค14101',
    academicYear: '2566',
    semester: '2',
    studentId: 'usr-1144',
    studentName: 'เด็กชายนเรศ หนูรุ่ง',
    studentCode: '1144',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    answers: { 'q-m4-1': 0, 'q-m4-2': 0 },
    itemResults: {
      'q-m4-1': { isCorrect: true, points: 10 },
      'q-m4-2': { isCorrect: true, points: 10 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2024-10-20T09:00:00Z',
    submittedAt: '2024-10-20T09:20:00Z',
    timeSpentSeconds: 1200,
    attemptNumber: 1
  },
  {
    id: 'sub-66-1144-s4',
    examId: 'ex-sci-p4-2566',
    examTitle: 'แบบทดสอบปลายภาค วิทยาศาสตร์ 4 (ปีการศึกษา 2566)',
    courseId: 'crs-sci-p4-2566',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 4 (ปีการศึกษา 2566)',
    courseCode: 'ว14101',
    academicYear: '2566',
    semester: '2',
    studentId: 'usr-1144',
    studentName: 'เด็กชายนเรศ หนูรุ่ง',
    studentCode: '1144',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    answers: { 'q-s4-66-1': 0, 'q-s4-66-2': 0 },
    itemResults: {
      'q-s4-66-1': { isCorrect: true, points: 10 },
      'q-s4-66-2': { isCorrect: true, points: 10 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2024-10-22T09:00:00Z',
    submittedAt: '2024-10-22T09:22:00Z',
    timeSpentSeconds: 1320,
    attemptNumber: 1
  },
  {
    id: 'sub-66-1089-m4',
    examId: 'ex-math-p4-2566',
    examTitle: 'แบบทดสอบปลายภาค คณิตศาสตร์ 4 (ปีการศึกษา 2566)',
    courseId: 'crs-math-p4-2566',
    courseName: 'คณิตศาสตร์ 4 (ปีการศึกษา 2566)',
    courseCode: 'ค14101',
    academicYear: '2566',
    semester: '2',
    studentId: 'usr-1089',
    studentName: 'นางสาวธัญญา กล้าหาญ',
    studentCode: '1089',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    answers: { 'q-m4-1': 0, 'q-m4-2': 0 },
    itemResults: {
      'q-m4-1': { isCorrect: true, points: 10 },
      'q-m4-2': { isCorrect: true, points: 10 }
    },
    score: 20,
    totalPoints: 20,
    percentage: 100,
    passed: true,
    startedAt: '2024-10-20T09:00:00Z',
    submittedAt: '2024-10-20T09:18:00Z',
    timeSpentSeconds: 1080,
    attemptNumber: 1
  },
  {
    id: 'sub-66-1145-s4',
    examId: 'ex-sci-p4-2566',
    examTitle: 'แบบทดสอบปลายภาค วิทยาศาสตร์ 4 (ปีการศึกษา 2566)',
    courseId: 'crs-sci-p4-2566',
    courseName: 'วิทยาศาสตร์และเทคโนโลยี 4 (ปีการศึกษา 2566)',
    courseCode: 'ว14101',
    academicYear: '2566',
    semester: '2',
    studentId: 'usr-1145',
    studentName: 'เด็กชายธนาภัทร ชูสำริด',
    studentCode: '1145',
    gradeLevel: 'ชั้นประถมศึกษาปีที่ 4',
    classRoom: 'ชั้นประถมศึกษาปีที่ 4/1',
    answers: { 'q-s4-66-1': 0, 'q-s4-66-2': 1 },
    itemResults: {
      'q-s4-66-1': { isCorrect: true, points: 10 },
      'q-s4-66-2': { isCorrect: false, points: 0 }
    },
    score: 10,
    totalPoints: 20,
    percentage: 50,
    passed: false,
    startedAt: '2024-10-22T09:00:00Z',
    submittedAt: '2024-10-22T09:25:00Z',
    timeSpentSeconds: 1500,
    attemptNumber: 1
  }
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'ยินดีต้อนรับสู่ระบบจัดการเรียนการสอนและสอบออนไลน์ LMS-KPS',
    content: 'ระบบ LMS-KPS โรงเรียนบ้านคลองพลูประชาสรรค์ พร้อมให้บริการครูและนักเรียนทุกระดับชั้น (ชั้นประถมศึกษาปีที่ 1 - ชั้นประถมศึกษาปีที่ 6) ในการจัดการเรียนรู้ การสอบ และติดตามพัฒนาการผู้เรียน',
    authorName: 'นายไพบูลย์ วงค์เมืองคำ (ผู้อำนวยการโรงเรียน)',
    authorRole: 'director',
    targetRole: 'all',
    priority: 'normal',
    createdAt: '2026-08-01T08:00:00Z',
  },
];
